# configs/exp_lr_2e-4_dropout_0.4.yaml
experiment_name: "exp_lr_2e-4_dropout_0.4"
optimizer: "AdamW"
initial_lr: 0.0002
weight_decay: 0.0003
num_epochs: 300
dropout_p: 0.4
region_weights: [1.0, 1.0, 2.0]
